steps:
  - input: "Select Environment"
    fields:
      - text: "Env env for Dev"
        key: "xdev"
      - text: "Env env for QA"
        key: "xqa"
  - wait
  - label: ":salesforce: $TEST_ENV"
    command: "run.sh"
